# Generated by Django 2.0 on 2020-04-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyappJd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('detail_url', models.CharField(max_length=250)),
                ('goodrate', models.CharField(db_column='goodRate', max_length=250)),
                ('pic_url', models.CharField(max_length=250)),
                ('types', models.CharField(max_length=250)),
                ('number_3_05', models.CharField(db_column='3.05', max_length=250)),
                ('number_3_06', models.CharField(db_column='3.06', max_length=250)),
                ('number_3_07', models.CharField(db_column='3.07', max_length=250)),
                ('number_3_08', models.CharField(db_column='3.08', max_length=250)),
                ('number_3_09', models.CharField(db_column='3.09', max_length=250)),
                ('number_3_10', models.CharField(db_column='3.10', max_length=250)),
                ('number_3_11', models.CharField(db_column='3.11', max_length=250)),
                ('number_3_12', models.CharField(db_column='3.12', max_length=250)),
                ('number_3_13', models.CharField(db_column='3.13', max_length=250)),
                ('number_3_14', models.CharField(db_column='3.14', max_length=250)),
                ('number_3_15', models.CharField(db_column='3.15', max_length=250)),
                ('max_today', models.CharField(blank=True, db_column='max/today', max_length=255, null=True)),
            ],
            options={
                'db_table': 'myapp_jd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HhhhUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('jifen', models.IntegerField(default='0')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
